#! /bin/sh
#
# Unix Bash variant of mbsiminit
# If editing this file, edit also the file mbsiminit,bat!
#
# Copyright (C) 2009 Markus Friedrich
#
# This library is free software; you can redistribute it and/or 
# modify it under the terms of the GNU Lesser General Public 
# License as published by the Free Software Foundation; either 
# version 2.1 of the License, or (at your option) any later version. 
#  
# This library is distributed in the hope that it will be useful, 
# but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU 
# Lesser General Public License for more details. 
#  
# You should have received a copy of the GNU Lesser General Public 
# License along with this library; if not, write to the Free Software 
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA
#
# Contact:
#   mafriedrich@users.berlios.de
#
#
# This file is only usefull for binary installations which are origianlly made
# to the directory /tmp/mbsim_local. In this case copy this directory to some
# other directory on some other machine and run this script
# ("source path/mbsiminit") ones in the shell to initialize the installation.

# get BINDIR
CURDIR=$(pwd)
cd $(dirname ${BASH_SOURCE[0]})
BINDIR=$(pwd)
cd $CURDIR
# get PREFIX
PREFIX=$(dirname $BINDIR)


# setup link
rm -f /tmp/mbsim_local
test -L /tmp/mbsim_local || ln -s $PREFIX /tmp/mbsim_local
# setup PATH and LD_LIBRARY_PATH
mbsimflatxml -h >& /dev/null || LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/tmp/mbsim_local/lib
mbsimflatxml -h >& /dev/null || PATH=$PATH:/tmp/mbsim_local/bin
export LD_LIBRARY_PATH
export PATH
