#define DRCHEK mbsim_DRCHEK
#define DROOTS mbsim_DROOTS
#define IXSAV  mbsim_IXSAV
#define DLSODE mbsim_DLSODE
#define DINTDY mbsim_DINTDY
#define XERRWD mbsim_XERRWD
#define DHELS  mbsim_DHELS
#define DHEQR  mbsim_DHEQR
#define XSETF  mbsim_XSETF
#define DATV   mbsim_DATV  
