#ifndef _MBSIMPOWERTRAIN_DEFINES_H_
#define _MBSIMPOWERTRAIN_DEFINES_H_

#define MBSIMPOWERTRAINNS_ "http://mbsim.berlios.de/MBSimPowertrain"
#define MBSIMPOWERTRAINNS "{"MBSIMPOWERTRAINNS_"}"

#endif
